version: '3.9'
services:
  app: 
    container_name: natours
    build: .
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/app/public
      - ./views:/app/views
      - ./data:/app/data
      - ./config:/app/config
      - ./controllers:/app/controllers
      - ./models:/app/models
      - ./routes:/app/routes
      - ./utils:/app/utils
      - ./app.js:/app/app.js
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./node_modules/:/app/node_modules/

    ports:
      - 3000:3000
